language: cpp

os: linux

sudo: false

arch:
  - arm64
  - ppc64le
  - s390x

script:
  - ./autogen.sh && make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - autopoint
